### ISSUE TITLE
[Bug] Broken links on api web page

### ISSUE THREAD

**Issue by schaafjs** [arx-deidentifier/arx-help#3]
The three URLs mentioned [at the bottom](https://arx.deidentifier.org/development/api/#a8) of [https://arx.deidentifier.org/development/api/](https://arx.deidentifier.org/development/api/), namely the section "Javadoc" lead to 404 errors.

It seems like the correct URLs (which can be found one page up on [https://arx.deidentifier.org/development/](https://arx.deidentifier.org/development/)) do not contain `development/` in their bodies.

Since the issue has to do with help/documentation I have opened it here instead of in the main repository.
Feel free to move/close the issue of if this is not the case.

**Comment by prasser** [comment]
Thanks a lot for reporting this - should be fixed now!

**Comment by schaafjs** [comment]
Can indeed confirm that all links work now. Thanks for the fast response!
