### ISSUE TITLE
[Bug] localrecording is not available anymore

### ISSUE THREAD

**Issue by idhamari** [arx-deidentifier/arx-help#6]
In [Utility Analysis section 3.10](https://github.com/arx-deidentifier/arx-help/blob/master/help/v3.9.1/utility/localrecoding.html), there is no local recording anymore.

It seems the section is moved to the "Configure transform" perspective to "Coding model" next to "General settings"

<img width="483" alt="p0510_01_analyze_8" src="https://user-images.githubusercontent.com/28802516/199261974-9abb0f46-428d-45d8-9dcd-0eee0204ccd2.png">

Moreover, there is no button "Perform local recording" as in the help ![figure](https://github.com/arx-deidentifier/arx-help/raw/master/help/v3.9.1/img/utility/analyze_8.png)

Is it still possible to do a local recording? if yes, how?

**Comment by prasser** [comment]
> It seems the section is moved to the "Configure transform" perspective to "Coding model" next to "General settings"

True.

> Is it still possible to do a local recording? if yes, how?

Through the options shown when clicking "Edit -> Anonymize".

**Comment by idhamari** [comment]
Thanks for your quick reply.

**Comment by idhamari** [comment]
Fixed in the recent [update](https://github.com/arx-deidentifier/arx-help/pull/5/commits/b59180620548ddc25708c930070ad67b0a4179a5). The page is modified.
